### ISSUE TITLE
Race Condition with Blobfuse Mount and CI SetupScript

### ISSUE THREAD

**Issue by ezwiefel** [Azure/feast-azure#17]
When trying to clone the feast-azure repo, I'm running into a race condition - where the Users directory hasn't yet been mounted to the CI when the `cd /home/azureuser/cloudfiles/code/Users` portion of the script is run.

Here's the error in the logs...
```
Successfully installed pymssql-2.2.2
/mnt/batch/tasks/startup/wd/scripts/creation.sh: line 1: cd: /home/azureuser/cloudfiles/code/Users: No such file or directory
Cloning into 'feast-azure'...
```

**Comment by ezwiefel** [comment]
I just realized that the Synapse deployment script doesn't have that - it's still in the SQL DB deployment script.

**Comment by samuel100** [comment]
@ezwiefel - thanks for raising. That is right, there is a race condition on the User's directory for the tutorial when deploying a SQL DB (rather than Synapse). The ARM template (on this line)[https://github.com/Azure/feast-azure/blob/7b06f3b2f73a8840bfec71d674763283e4e9cf9c/provider/cloud/fs_sqldb_azuredeploy.json#L213] needs to be updated to:

```json
"scriptData": "[base64('conda activate azureml_py38;pip install feast-azure-provider)]"
```

Then git clone the tutorial.
